routes:
  /about/:
    template: about
  /community/:
    template: community
  /blog/:
    template: blog

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
