routes:
  /about/:
    template: about
  /network/:
    template: network
  /blog/:
    template: blog
  /events/:
    template: events
collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/

