routes:
  /about/:
    template: about
  /network/:
    template: network
  /blog/:
    template: blog
  /events/:
    template: events
  /freelancers-form/:
    template: freelancers-form
  /non-profits-form/:
    template: non-profits-form
  /tech-vendor-form/:
    template: tech-vendor-form
collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
